kernelci/kernelci-build-staging

- build.py
Enable a combination of git commands and environment variables to
gather the global build info:
* add the -g option to enable calling git if a .git directory is
present and get the build info this way
* make the -e option look in the environment for values to override
what was found by git if -g was also enabled
This is necessary in particular when running a git bisection to
explicitly provide the git branch when calling the script while the
repository is in a detached HEAD, while still running "git describe"
and "git url" to get the other pieces of information.
Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>
Fixes: 4b83734b1b4f2f35ae36e5426143e570ab838259
> build.py: add -g option to use git as well as environment variables

- wget_retry.sh
* wget supports the HSTS header and stores the entries in a file
called .wget-hsts. Force wget to not obey the header and its
database in order to make sure it is accessing what it is told to.
> wget: Do not obey the HSTS database

- jenkins/kernel-defconfig-creator.sh
Since nobody is really validating, checking the various fragments for
stable trees, simplify the number of defconfigs built to just the
in-tree defconfigs.
The goal here is to get to stable boot reports that are useful
using defconfigs that people care about.
> jenkins: defconfig-creator: simplify stable buidls

- build.py
When the `-s' (silent) option is used, do not blast the log with the
list of all the dtb files etc... as they make the build log much
harder to read.  The build.log file should already contain all this
detailed information.
Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>
> Be more silent when -s is used

- jenkins/kernel-defconfig-creator.sh
Start thinning out defconfigs built to a minimal set.
Goal is to get importatn defconfig configurations into the kernel source
under configs/ and build them when present.
> jenkins/defconfig-creator: major thinning of defconfigs

- jenkins/kernel-arch-complete.sh
- jenkins/kernel-trigger-tarball.sh
Notifications will be only sent to him, and there's a shorter delay in
sending results because it will be only used in staging.
> Add Tomeu's tree

- vars/buildImage.groovy
Fixes docker/debos builds for non-x86
> vars/buildImage: fix group id

- jenkins/kernel-defconfig-creator.sh
Check for kconfig fragment kernel/configs/debug.config and add it to the
list of defconfigs to build if present.
Currently, upstream trees do not yet have this fragment, but it has been
discussed a few times.  So, currently it will not add additional builds
for upstream trees.
> jenkins: defconfig-creator: check/build debug fragments

- jenkins/debian/Jenkinsfile
- jenkins/debian/Jenkinsfile_stretchtests
The shared libraries are now declared directly in the global jenkins configuration in staging.
> debian/Jenkinsfiles: use shared libraries declared in Jenkins

- build.py
Use the more portable GNU tool `nproc` rather than grepping
/proc/cpuinfo directly.
> build.py: use nproc rather than grepping /proc/cpuinfo

- jenkins/debian/debos/overlays/networkd/etc/systemd/network/wired.network
See https://groups.io/g/kernelci/message/16
> debos/overlays/networkd: do not re-initialise network when using NFS root

- build.py
When do_post_retry() fails, abort instead of silently not pushing the
build results to the backend.
> build.py: abort when failure to talk to backend API

- vars/buildImage.groovy
This PR is addressing the discussion at https://github.com/kernelci/kernelci-build-staging/pull/35
There are two commits:
* The first one merely uses parameters instead of hard-coding values as agreed in the link above.
* The second commit will create the parameters automatically in the jenkins UI (in the part job configuration screen). This is done during the first run of the job when it'll also clear all the existing parameters of the job. 
IMPORTANT: This means the job will have to be always run a second time after its setup to have the "Build with parameters" menu available and that any parameter defined for its first run will be removed or updated. This should make handling the parameters for every job easier!
> Use job parameters and add then automatically in the job configuration

- jenkins/build.jpl
Leave the "trigger" node for trigger jobs, and run the build jobs on
the "shared-builder" nodes instead.
This means one executor on these nodes will be used to run the
top-level job while others will run individual kernel build stages.
The utilisation of the builders should not be impacted as long as
there are enough executors set up on them.
Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>
> T9828 build.jpl: run the job on shared-builder nodes rathern than trigger

- jenkins/build-trigger.jpl
- jenkins/build.jpl
- src/org/kernelci/build/Kernel.groovy
- src/org/kernelci/util/Job.groovy
Convert `kernel-defconfig-creator` as a Jenkins Pipeline job `build-trigger.jpl` and improve `build.jpl`:
* only build one kernel (arch / defconfig) in `build.jpl`
* trigger all the builds in `build-trigger.jpl` and trigger `kernel-arch-complete` at the end
* create shared library files in `src/org/kernelci` to reuse functions in other jobs
* keep the kernel builds on `shared-builder` and run build trigger on `defconfig-creator` nodes
> T9827 kernel build trigger

- jenkins/build.jpl
The kernelci-gtucker library name was only temporary to test the new
job on staging.
Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>
Fixes: 75c4b6bfc31b ("build.jpl: only build one defconfig and do not schedule build report")
> T7303 FIXUP build.jpl: fix kernelci lib import name

- jenkins/build-trigger.jpl
- jenkins/build.jpl
Rename the parallel task names to more descriptive values, so the
jenkins console output is more readable by humans who haven't read the
groovy code.
> build pipeline: more descriptive task names

- build.py
- jenkins/build.jpl
This is to reshape how regular builds are run:
* add `build.py -j` option to specify the number of parallel builds like in `make -j`
* add `PARALLEL_BUILDS` option to the `kernel-build` job to set this value
* do not hold the build lock any more, and extend build timeout to 3h
* run on `builder` nodes rather than `shared-builder`
The principle being that each `builder` node can have its number of executors set to `$(ncores)` / (-j value).  This is to maximise the available resources, especially on builders with over 16 CPU cores as `make -j` does not scale well above that.  A good value to start with would be `-j4`, so builders with 10 cores would have 3 executors, 16 cores 4 executors, 128 cores 32 executors etc...  Another limit is the available disk (or RAM) space as each …
> T10166 no build lock

- jenkins/debian/debos/scripts/stretchtests.sh
kms_cursor_legacy is also helpful when running the IGT testsuite.
Signed-off-by: Ana Guerrero Lopez <ana.guerrero@collabora.com>
> debian/debos/scripts/stretchtests.sh Add kms_cursor_legacy to the image

- build.py
For future build-time optimization, track the number of build threads
(make -j level) for every build.
New build.json field: build_threads
Along with build time, this data can be used to optimize build
throughput across the various build servers.
> build.py: add build threads to metadata

- jenkins/debian/Jenkinsfile_stretchtests
- jenkins/debian/debos/scripts/stretchtests.sh
This is a new requirement for IGT GPU Tools.
This will fix building the testsuites rootfs that's broken in production.
> stretch test rootfs: add libssl to the build-deps and on runtine

- jenkins/debian/Jenkinsfile_stretchtests
- jenkins/debian/debos/scripts/stretchtests.sh
This is a new requirement for IGT GPU Tools.
Staging is building new images using this branch and it works OK.
> stretch test rootfs: add libdw-dev and liblzma-dev to the build-deps and on runtine
